const fs = require('fs');
const jose = require('node-jose');
const path = require('path');

async function generate() {
  try {
    console.log('Generating new RSA key pair...');
    const keystore = jose.JWK.createKeyStore();
    const key = await keystore.generate('RSA', 2048, { alg: 'RS256', use: 'sig', kid: `feedback-key-${Date.now()}` });
    
    const jwks = keystore.toJSON();
    const publicKey = jwks.keys[0];

    const filePath = path.join('/app/api/lti/jwks/route.js');
    
    // The content for the new route.js file
    const fileContent = `// app/api/lti/jwks/route.js
import { NextResponse } from 'next/server';

export async function GET(req) {
  // Generated by the assistant on ${new Date().toISOString()}
  const jwk = {
    keys: [
      ${JSON.stringify(publicKey, null, 2)}
    ]
  };
  return NextResponse.json(jwk);
}`;

    console.log(`Updating ${filePath}...`);
    fs.writeFileSync(filePath, fileContent.trim());

    console.log('\\nSuccessfully updated jwks/route.js with the new public key:');
    console.log(JSON.stringify(publicKey, null, 2));
    console.log('\\nKey generation complete.');

  } catch (error) {
    console.error('An error occurred during key generation:', error);
    process.exit(1);
  }
}

generate(); 