export default class Bridge {
    focusedEditor: any;
    resolveEditorRendered: ((value: any) => void) | null;
    _editorRendered: Promise<any>;
    trayProps: WeakMap<WeakKey, any>;
    userLocale: string;
    _controller: {};
    _uploadMediaTranslations: {
        UploadMediaStrings: {
            ADD_CLOSED_CAPTIONS_OR_SUBTITLES: string;
            CLEAR_FILE_TEXT: string;
            CLOSE_TEXT: string;
            CLOSED_CAPTIONS_CHOOSE_FILE: string;
            CLOSED_CAPTIONS_SELECT_LANGUAGE: string;
            COMPUTER_PANEL_TITLE: string;
            DRAG_DROP_CLICK_TO_BROWSE: string;
            DRAG_FILE_TEXT: string;
            EMBED_PANEL_TITLE: string;
            EMBED_VIDEO_CODE_TEXT: string;
            INVALID_FILE_TEXT: string;
            LOADING_MEDIA: string;
            RECORD_PANEL_TITLE: string;
            SUBMIT_TEXT: string;
            UPLOADING_ERROR: string;
            UPLOAD_MEDIA_LABEL: string;
            MEDIA_RECORD_NOT_AVAILABLE: string;
            SUPPORTED_FILE_TYPES: string;
            NO_FILE_CHOSEN: string;
            REMOVE_FILE: string;
            ADD_NEW_CAPTION_OR_SUBTITLE: string;
            ADDED_CAPTION: string;
            DELETED_CAPTION: string;
            PROGRESS_LABEL: string;
            SELECT_SUPPORTED_FILE_TYPE: string;
            CHOOSE_FILE_TO_UPLOAD: string;
            ENTER_FILE_NAME: string;
        };
        SelectStrings: {
            USE_ARROWS: string;
            LIST_COLLAPSED: string;
            LIST_EXPANDED: string;
            OPTION_SELECTED: string;
        };
        MediaCaptureStrings: {
            ARIA_TIMEBAR_LABEL: string;
            ARIA_VIDEO_LABEL: string;
            ARIA_VOLUME: string;
            ARIA_RECORDING: string;
            DEFAULT_ERROR: string;
            DEVICE_AUDIO: string;
            DEVICE_VIDEO: string;
            FILE_PLACEHOLDER: string;
            FINISH: string;
            WEBCAM_VIDEO_SELECTION_LABEL: string;
            WEBCAM_AUDIO_SELECTION_LABEL: string;
            NO_WEBCAM: string;
            NOT_ALLOWED_ERROR: string;
            NOT_READABLE_ERROR: string;
            PLAYBACK_PAUSE: string;
            PLAYBACK_PLAY: string;
            PREVIEW: string;
            SAVE_MEDIA: string;
            SR_FILE_INPUT: string;
            START: string;
            START_OVER: string;
            SCREEN_DEFAULT_ERROR: string;
            MIC_BLOCKED: string;
            WEBCAM_BLOCKED: string;
            MIC_AND_WEBCAM_BLOCKED: string;
            NO_MIC_EXIST: string;
            NO_WEBCAM_EXIST: string;
            NO_MIC_AND_WEBCAM_EXIST: string;
            WEBCAM_DISABLED: string;
            MICROPHONE_DISABLED: string;
            SYSTEM_AUDIO_ALLOWED: string;
            SYSTEM_AUDIO_DISABLED: string;
        };
    } | null;
    _canvasOrigin: string;
    get editorRendered(): Promise<any>;
    controller(editorId: any): any;
    activeEditor(): any;
    focusEditor(editor: any): void;
    blurEditor(editor: any): void;
    focusActiveEditor(skipFocus?: boolean): void;
    get mediaServerSession(): any;
    get mediaServerUploader(): K5Uploader | null | undefined;
    setMediaServerSession(session: any): void;
    _mediaServerSession: any;
    _mediaServerUploader: K5Uploader | null | undefined;
    set canvasOrigin(origin: string);
    get canvasOrigin(): string;
    get uploadMediaTranslations(): {
        UploadMediaStrings: {
            ADD_CLOSED_CAPTIONS_OR_SUBTITLES: string;
            CLEAR_FILE_TEXT: string;
            CLOSE_TEXT: string;
            CLOSED_CAPTIONS_CHOOSE_FILE: string;
            CLOSED_CAPTIONS_SELECT_LANGUAGE: string;
            COMPUTER_PANEL_TITLE: string;
            DRAG_DROP_CLICK_TO_BROWSE: string;
            DRAG_FILE_TEXT: string;
            EMBED_PANEL_TITLE: string;
            EMBED_VIDEO_CODE_TEXT: string;
            INVALID_FILE_TEXT: string;
            LOADING_MEDIA: string;
            RECORD_PANEL_TITLE: string;
            SUBMIT_TEXT: string;
            UPLOADING_ERROR: string;
            UPLOAD_MEDIA_LABEL: string;
            MEDIA_RECORD_NOT_AVAILABLE: string;
            SUPPORTED_FILE_TYPES: string;
            NO_FILE_CHOSEN: string;
            REMOVE_FILE: string;
            ADD_NEW_CAPTION_OR_SUBTITLE: string;
            ADDED_CAPTION: string;
            DELETED_CAPTION: string;
            PROGRESS_LABEL: string;
            SELECT_SUPPORTED_FILE_TYPE: string;
            CHOOSE_FILE_TO_UPLOAD: string;
            ENTER_FILE_NAME: string;
        };
        SelectStrings: {
            USE_ARROWS: string;
            LIST_COLLAPSED: string;
            LIST_EXPANDED: string;
            OPTION_SELECTED: string;
        };
        MediaCaptureStrings: {
            ARIA_TIMEBAR_LABEL: string;
            ARIA_VIDEO_LABEL: string;
            ARIA_VOLUME: string;
            ARIA_RECORDING: string;
            DEFAULT_ERROR: string;
            DEVICE_AUDIO: string;
            DEVICE_VIDEO: string;
            FILE_PLACEHOLDER: string;
            FINISH: string;
            WEBCAM_VIDEO_SELECTION_LABEL: string;
            WEBCAM_AUDIO_SELECTION_LABEL: string;
            NO_WEBCAM: string;
            NOT_ALLOWED_ERROR: string;
            NOT_READABLE_ERROR: string;
            PLAYBACK_PAUSE: string;
            PLAYBACK_PLAY: string;
            PREVIEW: string;
            SAVE_MEDIA: string;
            SR_FILE_INPUT: string;
            START: string;
            START_OVER: string;
            SCREEN_DEFAULT_ERROR: string;
            MIC_BLOCKED: string;
            WEBCAM_BLOCKED: string;
            MIC_AND_WEBCAM_BLOCKED: string;
            NO_MIC_EXIST: string;
            NO_WEBCAM_EXIST: string;
            NO_MIC_AND_WEBCAM_EXIST: string;
            WEBCAM_DISABLED: string;
            MICROPHONE_DISABLED: string;
            SYSTEM_AUDIO_ALLOWED: string;
            SYSTEM_AUDIO_DISABLED: string;
        };
    };
    detachEditor(editor: any): void;
    getEditor(): any;
    renderEditor(editor: any): void;
    attachController(controller: any, editorId: any): void;
    detachController(editorId: any): void;
    showTrayForPlugin(plugin: any, editorId: any): void;
    hideTrays(): void;
    existingContentToLink(): any;
    existingContentToLinkIsImg(): any;
    insertLink: (link: any) => void;
    insertFileLink: (link: any) => any;
    insertImage(image: any): any;
    insertImagePlaceholder(fileMetaProps: any): void;
    removePlaceholders(name: any): void;
    showError(err: any): void;
    embedImage: (image: any) => void;
    embedMedia: (media: any) => void;
    insertEmbedCode: (embedCode: any) => void;
    insertVideo: (video: any) => void;
    insertAudio: (audio: any) => void;
}
import { K5Uploader } from '@instructure/k5uploader';
